name: Upload test website to S3 and Invalidate CloudFront Cache

on:
  push:
    branches:
      - test-bucket

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    
    - name: Deploy to S3
      run: |
        aws s3 sync ./galazkar.com s3://${{ secrets.TEST_AWS_S3_BUCKET }} --delete
    
    - name: Invalidate CloudFront Cache
      run: |
        aws cloudfront create-invalidation \
          --distribution-id ${{ secrets.TEST_CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"